name: Build and Run Frontend

on:
  push:
    branches: main
    
jobs:
  deploy-frontend:
    runs-on: self-hosted
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        cd frontend
        docker build -t tracker-app:v1 .

    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        sudo mv ./bin/trivy /usr/local/bin/
 
    - name: Run Trivy Scan
      run: |
        trivy image --severity HIGH,CRITICAL tracker-app:v1 || exit 1

    - name: Run new container
      run: |
        docker run -d --name tracker-app -p 80:80 tracker-app:v1